name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '1 8 * * *'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    env:
      GOLANGCILINT_VERSION: v2.4.0

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: './go.mod'

      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: ${{ env.GOLANGCILINT_VERSION }}
          skip-cache: true
          args: --timeout=10m

  test:
    name: Test
    runs-on: ubuntu-latest

    env:
      CGO_ENABLED: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: './go.mod'

      - name: Test
        run: |
          make test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.out
          token: ${{ secrets.CODECOV_TOKEN }}

  test-e2e:
    name: E2E (Cloud) Test
    runs-on: ubuntu-latest

    env:
      SDK_ALTA_USER: ${{ secrets.SDK_ALTA_USER }}
      SDK_ALTA_PASS: ${{ secrets.SDK_ALTA_PASS }}
      SDK_ALTA_SITE: ${{ secrets.SDK_ALTA_SITE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: './go.mod'

      - name: E2E Test
        run: |
          make test-e2e

#      - name: Upload coverage to Codecov
#        uses: codecov/codecov-action@v5
#        with:
#          files: ./coverage-e2e.out
#          token: ${{ secrets.CODECOV_TOKEN }}

  run-example:
    name: Run example/basic/main.go
    runs-on: ubuntu-latest

    env:
      SDK_ALTA_USER: ${{ secrets.SDK_ALTA_USER }}
      SDK_ALTA_PASS: ${{ secrets.SDK_ALTA_PASS }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: './go.mod'

      - name: Run Example
        run: |
          make run-example
